### ISSUE TITLE
"trigger firenvim" keyboard shortcut is confused about frames

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#857]
I'm currently playing with using [markdown-here](https://markdown-here.com/) to make rich text html easier to write without gui buttons. You know that I love firenvim, so I'd love to use it to edit the markdown in such boxes. However, manually triggering firenvim on such a box opens up a blank buffer. The text isn't transferred.

Would it be possible to create edge case logic for these boxes to get the text into firenvim? (Even as plain text would be fine, because I would be treating it like markdown.)

An example is the box at [textbox.io](https://www.textbox.io/).

**Comment by glacambre** [comment]
Huh, funny, the following firenvim config works on textbox.io:
```
let g:firenvim_config = {
  \ 'localSettings': {
    \ '.*': {
      \  'selector': 'textarea:not([readonly]), div[role="textbox"], *[contenteditable=true]'
    \ }
  \ }
\ }
```

So the issue is really about the keyboard shortcut. I'll look into that, thanks for the report :)

**Comment by glacambre** [comment]
Should be fixed on master, I'll publish a release either tomorrow or the day after :)

**Comment by BlueDrink9** [comment]
You are so good

**Comment by BlueDrink9** [comment]
Just updated to 0.2.0, firenvim now crashes after propagating text back to textbox.io. The file seems to already exist, and it crashes when I force an overwrite too.
firenvim 0.2.0 on nvim 0.4.3

The same is not true of markdown boxes like this one, even though I still get an overwrite warning the first time I open it.

**Comment by glacambre** [comment]
What does crashing mean here? Does the neovim frame hang, something else? I can't reproduce this issue on any of the websites you submitted in the OP, does your problem happen on another website?

**Comment by glacambre** [comment]
Oh, I think I see what you mean, plain `:w` makes the firenvim frame disappear. Funny, I only tried it with `:wq` :)

**Comment by glacambre** [comment]
There, should be fixed for real now. I'll publish a new release whenever I manage to fix the renderer issues (hopefully today).
